hdfs dfs -rm -r -skipTrash /YieldWorkflow

hadoop fs -put yieldIngestWorkflow.xml /YieldWorkflow/yieldIngestWorkflow.xml
 
hadoop fs -put CreateSimple__SPML_ModuleInfo.sh /YieldWorkflow/CreateSimple__SPML_ModuleInfo.sh
hadoop fs -put IngestSimple__SPML_ModuleInfo_SPMX.sh /YieldWorkflow/IngestSimple__SPML_ModuleInfo_SPMX.sh
hadoop fs -put IngestSimple__SPML_ModuleInfo_SPMM.sh /YieldWorkflow/IngestSimple__SPML_ModuleInfo_SPMM.sh
hadoop fs -put IngestSimple__SPML_ModuleInfo_SPDV.sh /YieldWorkflow/IngestSimple__SPML_ModuleInfo_SPDV.sh
hadoop fs -put IngestSimple__SPML_ModuleInfo_SPTT.sh /YieldWorkflow/IngestSimple__SPML_ModuleInfo_SPTT.sh
hadoop fs -put IngestSimple__SPML_ModuleInfo_SPTM.sh /YieldWorkflow/IngestSimple__SPML_ModuleInfo_SPTM.sh
hadoop fs -put CreateSimple_Address.sh /YieldWorkflow/CreateSimple_Address.sh
hadoop fs -put IngestSimple_Address_SPMX.sh /YieldWorkflow/IngestSimple_Address_SPMX.sh
hadoop fs -put IngestSimple_Address_SPMM.sh /YieldWorkflow/IngestSimple_Address_SPMM.sh
hadoop fs -put IngestSimple_Address_SPDV.sh /YieldWorkflow/IngestSimple_Address_SPDV.sh
hadoop fs -put IngestSimple_Address_SPTT.sh /YieldWorkflow/IngestSimple_Address_SPTT.sh
hadoop fs -put IngestSimple_Address_SPTM.sh /YieldWorkflow/IngestSimple_Address_SPTM.sh
hadoop fs -put CreateSimple_Customer.sh /YieldWorkflow/CreateSimple_Customer.sh
hadoop fs -put IngestSimple_Customer_SPMX.sh /YieldWorkflow/IngestSimple_Customer_SPMX.sh
hadoop fs -put IngestSimple_Customer_SPMM.sh /YieldWorkflow/IngestSimple_Customer_SPMM.sh
hadoop fs -put IngestSimple_Customer_SPDV.sh /YieldWorkflow/IngestSimple_Customer_SPDV.sh
hadoop fs -put IngestSimple_Customer_SPTT.sh /YieldWorkflow/IngestSimple_Customer_SPTT.sh
hadoop fs -put IngestSimple_Customer_SPTM.sh /YieldWorkflow/IngestSimple_Customer_SPTM.sh
hadoop fs -put CreateSimple_Department.sh /YieldWorkflow/CreateSimple_Department.sh
hadoop fs -put IngestSimple_Department_SPMX.sh /YieldWorkflow/IngestSimple_Department_SPMX.sh
hadoop fs -put IngestSimple_Department_SPMM.sh /YieldWorkflow/IngestSimple_Department_SPMM.sh
hadoop fs -put IngestSimple_Department_SPDV.sh /YieldWorkflow/IngestSimple_Department_SPDV.sh
hadoop fs -put IngestSimple_Department_SPTT.sh /YieldWorkflow/IngestSimple_Department_SPTT.sh
hadoop fs -put IngestSimple_Department_SPTM.sh /YieldWorkflow/IngestSimple_Department_SPTM.sh
hadoop fs -put CreateSimple_InvIsolatedReason.sh /YieldWorkflow/CreateSimple_InvIsolatedReason.sh
hadoop fs -put IngestSimple_InvIsolatedReason_SPMX.sh /YieldWorkflow/IngestSimple_InvIsolatedReason_SPMX.sh
hadoop fs -put IngestSimple_InvIsolatedReason_SPMM.sh /YieldWorkflow/IngestSimple_InvIsolatedReason_SPMM.sh
hadoop fs -put IngestSimple_InvIsolatedReason_SPDV.sh /YieldWorkflow/IngestSimple_InvIsolatedReason_SPDV.sh
hadoop fs -put IngestSimple_InvIsolatedReason_SPTT.sh /YieldWorkflow/IngestSimple_InvIsolatedReason_SPTT.sh
hadoop fs -put IngestSimple_InvIsolatedReason_SPTM.sh /YieldWorkflow/IngestSimple_InvIsolatedReason_SPTM.sh
hadoop fs -put CreateSimple_InvState.sh /YieldWorkflow/CreateSimple_InvState.sh
hadoop fs -put IngestSimple_InvState_SPMX.sh /YieldWorkflow/IngestSimple_InvState_SPMX.sh
hadoop fs -put IngestSimple_InvState_SPMM.sh /YieldWorkflow/IngestSimple_InvState_SPMM.sh
hadoop fs -put IngestSimple_InvState_SPDV.sh /YieldWorkflow/IngestSimple_InvState_SPDV.sh
hadoop fs -put IngestSimple_InvState_SPTT.sh /YieldWorkflow/IngestSimple_InvState_SPTT.sh
hadoop fs -put IngestSimple_InvState_SPTM.sh /YieldWorkflow/IngestSimple_InvState_SPTM.sh
hadoop fs -put CreateSimple_LineGroup.sh /YieldWorkflow/CreateSimple_LineGroup.sh
hadoop fs -put IngestSimple_LineGroup_SPMX.sh /YieldWorkflow/IngestSimple_LineGroup_SPMX.sh
hadoop fs -put IngestSimple_LineGroup_SPMM.sh /YieldWorkflow/IngestSimple_LineGroup_SPMM.sh
hadoop fs -put IngestSimple_LineGroup_SPDV.sh /YieldWorkflow/IngestSimple_LineGroup_SPDV.sh
hadoop fs -put IngestSimple_LineGroup_SPTT.sh /YieldWorkflow/IngestSimple_LineGroup_SPTT.sh
hadoop fs -put IngestSimple_LineGroup_SPTM.sh /YieldWorkflow/IngestSimple_LineGroup_SPTM.sh
hadoop fs -put CreateSimple_LineInfo.sh /YieldWorkflow/CreateSimple_LineInfo.sh
hadoop fs -put IngestSimple_LineInfo_SPMX.sh /YieldWorkflow/IngestSimple_LineInfo_SPMX.sh
hadoop fs -put IngestSimple_LineInfo_SPMM.sh /YieldWorkflow/IngestSimple_LineInfo_SPMM.sh
hadoop fs -put IngestSimple_LineInfo_SPDV.sh /YieldWorkflow/IngestSimple_LineInfo_SPDV.sh
hadoop fs -put IngestSimple_LineInfo_SPTT.sh /YieldWorkflow/IngestSimple_LineInfo_SPTT.sh
hadoop fs -put IngestSimple_LineInfo_SPTM.sh /YieldWorkflow/IngestSimple_LineInfo_SPTM.sh
hadoop fs -put CreateSimple_LineSection.sh /YieldWorkflow/CreateSimple_LineSection.sh
hadoop fs -put IngestSimple_LineSection_SPMX.sh /YieldWorkflow/IngestSimple_LineSection_SPMX.sh
hadoop fs -put IngestSimple_LineSection_SPMM.sh /YieldWorkflow/IngestSimple_LineSection_SPMM.sh
hadoop fs -put IngestSimple_LineSection_SPDV.sh /YieldWorkflow/IngestSimple_LineSection_SPDV.sh
hadoop fs -put IngestSimple_LineSection_SPTT.sh /YieldWorkflow/IngestSimple_LineSection_SPTT.sh
hadoop fs -put IngestSimple_LineSection_SPTM.sh /YieldWorkflow/IngestSimple_LineSection_SPTM.sh
hadoop fs -put CreateSimple_LineType.sh /YieldWorkflow/CreateSimple_LineType.sh
hadoop fs -put IngestSimple_LineType_SPMX.sh /YieldWorkflow/IngestSimple_LineType_SPMX.sh
hadoop fs -put IngestSimple_LineType_SPMM.sh /YieldWorkflow/IngestSimple_LineType_SPMM.sh
hadoop fs -put IngestSimple_LineType_SPDV.sh /YieldWorkflow/IngestSimple_LineType_SPDV.sh
hadoop fs -put IngestSimple_LineType_SPTT.sh /YieldWorkflow/IngestSimple_LineType_SPTT.sh
hadoop fs -put IngestSimple_LineType_SPTM.sh /YieldWorkflow/IngestSimple_LineType_SPTM.sh
hadoop fs -put CreateSimple_MachineStageType.sh /YieldWorkflow/CreateSimple_MachineStageType.sh
hadoop fs -put IngestSimple_MachineStageType_SPMX.sh /YieldWorkflow/IngestSimple_MachineStageType_SPMX.sh
hadoop fs -put IngestSimple_MachineStageType_SPMM.sh /YieldWorkflow/IngestSimple_MachineStageType_SPMM.sh
hadoop fs -put IngestSimple_MachineStageType_SPDV.sh /YieldWorkflow/IngestSimple_MachineStageType_SPDV.sh
hadoop fs -put IngestSimple_MachineStageType_SPTT.sh /YieldWorkflow/IngestSimple_MachineStageType_SPTT.sh
hadoop fs -put IngestSimple_MachineStageType_SPTM.sh /YieldWorkflow/IngestSimple_MachineStageType_SPTM.sh
hadoop fs -put CreateSimple_MachineStop.sh /YieldWorkflow/CreateSimple_MachineStop.sh
hadoop fs -put IngestSimple_MachineStop_SPMX.sh /YieldWorkflow/IngestSimple_MachineStop_SPMX.sh
hadoop fs -put IngestSimple_MachineStop_SPMM.sh /YieldWorkflow/IngestSimple_MachineStop_SPMM.sh
hadoop fs -put IngestSimple_MachineStop_SPDV.sh /YieldWorkflow/IngestSimple_MachineStop_SPDV.sh
hadoop fs -put IngestSimple_MachineStop_SPTT.sh /YieldWorkflow/IngestSimple_MachineStop_SPTT.sh
hadoop fs -put IngestSimple_MachineStop_SPTM.sh /YieldWorkflow/IngestSimple_MachineStop_SPTM.sh
hadoop fs -put CreateSimple_MachineStopCategory.sh /YieldWorkflow/CreateSimple_MachineStopCategory.sh
hadoop fs -put IngestSimple_MachineStopCategory_SPMX.sh /YieldWorkflow/IngestSimple_MachineStopCategory_SPMX.sh
hadoop fs -put IngestSimple_MachineStopCategory_SPMM.sh /YieldWorkflow/IngestSimple_MachineStopCategory_SPMM.sh
hadoop fs -put IngestSimple_MachineStopCategory_SPDV.sh /YieldWorkflow/IngestSimple_MachineStopCategory_SPDV.sh
hadoop fs -put IngestSimple_MachineStopCategory_SPTT.sh /YieldWorkflow/IngestSimple_MachineStopCategory_SPTT.sh
hadoop fs -put IngestSimple_MachineStopCategory_SPTM.sh /YieldWorkflow/IngestSimple_MachineStopCategory_SPTM.sh
hadoop fs -put CreateSimple_MachineStopReason.sh /YieldWorkflow/CreateSimple_MachineStopReason.sh
hadoop fs -put IngestSimple_MachineStopReason_SPMX.sh /YieldWorkflow/IngestSimple_MachineStopReason_SPMX.sh
hadoop fs -put IngestSimple_MachineStopReason_SPMM.sh /YieldWorkflow/IngestSimple_MachineStopReason_SPMM.sh
hadoop fs -put IngestSimple_MachineStopReason_SPDV.sh /YieldWorkflow/IngestSimple_MachineStopReason_SPDV.sh
hadoop fs -put IngestSimple_MachineStopReason_SPTT.sh /YieldWorkflow/IngestSimple_MachineStopReason_SPTT.sh
hadoop fs -put IngestSimple_MachineStopReason_SPTM.sh /YieldWorkflow/IngestSimple_MachineStopReason_SPTM.sh
hadoop fs -put CreateSimple_Operation.sh /YieldWorkflow/CreateSimple_Operation.sh
hadoop fs -put IngestSimple_Operation_SPMX.sh /YieldWorkflow/IngestSimple_Operation_SPMX.sh
hadoop fs -put IngestSimple_Operation_SPMM.sh /YieldWorkflow/IngestSimple_Operation_SPMM.sh
hadoop fs -put IngestSimple_Operation_SPDV.sh /YieldWorkflow/IngestSimple_Operation_SPDV.sh
hadoop fs -put IngestSimple_Operation_SPTT.sh /YieldWorkflow/IngestSimple_Operation_SPTT.sh
hadoop fs -put IngestSimple_Operation_SPTM.sh /YieldWorkflow/IngestSimple_Operation_SPTM.sh
hadoop fs -put CreateSimple_OperationType.sh /YieldWorkflow/CreateSimple_OperationType.sh
hadoop fs -put IngestSimple_OperationType_SPMX.sh /YieldWorkflow/IngestSimple_OperationType_SPMX.sh
hadoop fs -put IngestSimple_OperationType_SPMM.sh /YieldWorkflow/IngestSimple_OperationType_SPMM.sh
hadoop fs -put IngestSimple_OperationType_SPDV.sh /YieldWorkflow/IngestSimple_OperationType_SPDV.sh
hadoop fs -put IngestSimple_OperationType_SPTT.sh /YieldWorkflow/IngestSimple_OperationType_SPTT.sh
hadoop fs -put IngestSimple_OperationType_SPTM.sh /YieldWorkflow/IngestSimple_OperationType_SPTM.sh
hadoop fs -put CreateSimple_PartClassification.sh /YieldWorkflow/CreateSimple_PartClassification.sh
hadoop fs -put IngestSimple_PartClassification_SPMX.sh /YieldWorkflow/IngestSimple_PartClassification_SPMX.sh
hadoop fs -put IngestSimple_PartClassification_SPMM.sh /YieldWorkflow/IngestSimple_PartClassification_SPMM.sh
hadoop fs -put IngestSimple_PartClassification_SPDV.sh /YieldWorkflow/IngestSimple_PartClassification_SPDV.sh
hadoop fs -put IngestSimple_PartClassification_SPTT.sh /YieldWorkflow/IngestSimple_PartClassification_SPTT.sh
hadoop fs -put IngestSimple_PartClassification_SPTM.sh /YieldWorkflow/IngestSimple_PartClassification_SPTM.sh
hadoop fs -put CreateSimple_PartSubClassification.sh /YieldWorkflow/CreateSimple_PartSubClassification.sh
hadoop fs -put IngestSimple_PartSubClassification_SPMX.sh /YieldWorkflow/IngestSimple_PartSubClassification_SPMX.sh
hadoop fs -put IngestSimple_PartSubClassification_SPMM.sh /YieldWorkflow/IngestSimple_PartSubClassification_SPMM.sh
hadoop fs -put IngestSimple_PartSubClassification_SPDV.sh /YieldWorkflow/IngestSimple_PartSubClassification_SPDV.sh
hadoop fs -put IngestSimple_PartSubClassification_SPTT.sh /YieldWorkflow/IngestSimple_PartSubClassification_SPTT.sh
hadoop fs -put IngestSimple_PartSubClassification_SPTM.sh /YieldWorkflow/IngestSimple_PartSubClassification_SPTM.sh
hadoop fs -put CreateSimple_PartType.sh /YieldWorkflow/CreateSimple_PartType.sh
hadoop fs -put IngestSimple_PartType_SPMX.sh /YieldWorkflow/IngestSimple_PartType_SPMX.sh
hadoop fs -put IngestSimple_PartType_SPMM.sh /YieldWorkflow/IngestSimple_PartType_SPMM.sh
hadoop fs -put IngestSimple_PartType_SPDV.sh /YieldWorkflow/IngestSimple_PartType_SPDV.sh
hadoop fs -put IngestSimple_PartType_SPTT.sh /YieldWorkflow/IngestSimple_PartType_SPTT.sh
hadoop fs -put IngestSimple_PartType_SPTM.sh /YieldWorkflow/IngestSimple_PartType_SPTM.sh
hadoop fs -put CreateSimple_Shift.sh /YieldWorkflow/CreateSimple_Shift.sh
hadoop fs -put IngestSimple_Shift_SPMX.sh /YieldWorkflow/IngestSimple_Shift_SPMX.sh
hadoop fs -put IngestSimple_Shift_SPMM.sh /YieldWorkflow/IngestSimple_Shift_SPMM.sh
hadoop fs -put IngestSimple_Shift_SPDV.sh /YieldWorkflow/IngestSimple_Shift_SPDV.sh
hadoop fs -put IngestSimple_Shift_SPTT.sh /YieldWorkflow/IngestSimple_Shift_SPTT.sh
hadoop fs -put IngestSimple_Shift_SPTM.sh /YieldWorkflow/IngestSimple_Shift_SPTM.sh
hadoop fs -put CreateSimple_ShiftPattern.sh /YieldWorkflow/CreateSimple_ShiftPattern.sh
hadoop fs -put IngestSimple_ShiftPattern_SPMX.sh /YieldWorkflow/IngestSimple_ShiftPattern_SPMX.sh
hadoop fs -put IngestSimple_ShiftPattern_SPMM.sh /YieldWorkflow/IngestSimple_ShiftPattern_SPMM.sh
hadoop fs -put IngestSimple_ShiftPattern_SPDV.sh /YieldWorkflow/IngestSimple_ShiftPattern_SPDV.sh
hadoop fs -put IngestSimple_ShiftPattern_SPTT.sh /YieldWorkflow/IngestSimple_ShiftPattern_SPTT.sh
hadoop fs -put IngestSimple_ShiftPattern_SPTM.sh /YieldWorkflow/IngestSimple_ShiftPattern_SPTM.sh
hadoop fs -put CreateSimple_ShiftType.sh /YieldWorkflow/CreateSimple_ShiftType.sh
hadoop fs -put IngestSimple_ShiftType_SPMX.sh /YieldWorkflow/IngestSimple_ShiftType_SPMX.sh
hadoop fs -put IngestSimple_ShiftType_SPMM.sh /YieldWorkflow/IngestSimple_ShiftType_SPMM.sh
hadoop fs -put IngestSimple_ShiftType_SPDV.sh /YieldWorkflow/IngestSimple_ShiftType_SPDV.sh
hadoop fs -put IngestSimple_ShiftType_SPTT.sh /YieldWorkflow/IngestSimple_ShiftType_SPTT.sh
hadoop fs -put IngestSimple_ShiftType_SPTM.sh /YieldWorkflow/IngestSimple_ShiftType_SPTM.sh
hadoop fs -put CreateSimple_Supplier.sh /YieldWorkflow/CreateSimple_Supplier.sh
hadoop fs -put IngestSimple_Supplier_SPMX.sh /YieldWorkflow/IngestSimple_Supplier_SPMX.sh
hadoop fs -put IngestSimple_Supplier_SPMM.sh /YieldWorkflow/IngestSimple_Supplier_SPMM.sh
hadoop fs -put IngestSimple_Supplier_SPDV.sh /YieldWorkflow/IngestSimple_Supplier_SPDV.sh
hadoop fs -put IngestSimple_Supplier_SPTT.sh /YieldWorkflow/IngestSimple_Supplier_SPTT.sh
hadoop fs -put IngestSimple_Supplier_SPTM.sh /YieldWorkflow/IngestSimple_Supplier_SPTM.sh
hadoop fs -put CreateSimple_TagList.sh /YieldWorkflow/CreateSimple_TagList.sh
hadoop fs -put IngestSimple_TagList_SPMX.sh /YieldWorkflow/IngestSimple_TagList_SPMX.sh
hadoop fs -put IngestSimple_TagList_SPMM.sh /YieldWorkflow/IngestSimple_TagList_SPMM.sh
hadoop fs -put IngestSimple_TagList_SPDV.sh /YieldWorkflow/IngestSimple_TagList_SPDV.sh
hadoop fs -put IngestSimple_TagList_SPTT.sh /YieldWorkflow/IngestSimple_TagList_SPTT.sh
hadoop fs -put IngestSimple_TagList_SPTM.sh /YieldWorkflow/IngestSimple_TagList_SPTM.sh
hadoop fs -put CreateSimple_Unit.sh /YieldWorkflow/CreateSimple_Unit.sh
hadoop fs -put IngestSimple_Unit_SPMX.sh /YieldWorkflow/IngestSimple_Unit_SPMX.sh
hadoop fs -put IngestSimple_Unit_SPMM.sh /YieldWorkflow/IngestSimple_Unit_SPMM.sh
hadoop fs -put IngestSimple_Unit_SPDV.sh /YieldWorkflow/IngestSimple_Unit_SPDV.sh
hadoop fs -put IngestSimple_Unit_SPTT.sh /YieldWorkflow/IngestSimple_Unit_SPTT.sh
hadoop fs -put IngestSimple_Unit_SPTM.sh /YieldWorkflow/IngestSimple_Unit_SPTM.sh

hadoop fs -put CreateJoin_.sh /YieldWorkflow/CreateJoin_.sh
hadoop fs -put IngestJoin__SPMX.sh /YieldWorkflow/IngestJoin__SPMX.sh
hadoop fs -put IngestJoin__SPMM.sh /YieldWorkflow/IngestJoin__SPMM.sh
hadoop fs -put IngestJoin__SPDV.sh /YieldWorkflow/IngestJoin__SPDV.sh
hadoop fs -put IngestJoin__SPTT.sh /YieldWorkflow/IngestJoin__SPTT.sh
hadoop fs -put IngestJoin__SPTM.sh /YieldWorkflow/IngestJoin__SPTM.sh
hadoop fs -put CreateJoin_.sh /YieldWorkflow/CreateJoin_.sh
hadoop fs -put IngestJoin__SPMX.sh /YieldWorkflow/IngestJoin__SPMX.sh
hadoop fs -put IngestJoin__SPMM.sh /YieldWorkflow/IngestJoin__SPMM.sh
hadoop fs -put IngestJoin__SPDV.sh /YieldWorkflow/IngestJoin__SPDV.sh
hadoop fs -put IngestJoin__SPTT.sh /YieldWorkflow/IngestJoin__SPTT.sh
hadoop fs -put IngestJoin__SPTM.sh /YieldWorkflow/IngestJoin__SPTM.sh
hadoop fs -put CreateJoin_.sh /YieldWorkflow/CreateJoin_.sh
hadoop fs -put IngestJoin__SPMX.sh /YieldWorkflow/IngestJoin__SPMX.sh
hadoop fs -put IngestJoin__SPMM.sh /YieldWorkflow/IngestJoin__SPMM.sh
hadoop fs -put IngestJoin__SPDV.sh /YieldWorkflow/IngestJoin__SPDV.sh
hadoop fs -put IngestJoin__SPTT.sh /YieldWorkflow/IngestJoin__SPTT.sh
hadoop fs -put IngestJoin__SPTM.sh /YieldWorkflow/IngestJoin__SPTM.sh
hadoop fs -put CreateJoin_.sh /YieldWorkflow/CreateJoin_.sh
hadoop fs -put IngestJoin__SPMX.sh /YieldWorkflow/IngestJoin__SPMX.sh
hadoop fs -put IngestJoin__SPMM.sh /YieldWorkflow/IngestJoin__SPMM.sh
hadoop fs -put IngestJoin__SPDV.sh /YieldWorkflow/IngestJoin__SPDV.sh
hadoop fs -put IngestJoin__SPTT.sh /YieldWorkflow/IngestJoin__SPTT.sh
hadoop fs -put IngestJoin__SPTM.sh /YieldWorkflow/IngestJoin__SPTM.sh
hadoop fs -put CreateJoin_.sh /YieldWorkflow/CreateJoin_.sh
hadoop fs -put IngestJoin__SPMX.sh /YieldWorkflow/IngestJoin__SPMX.sh
hadoop fs -put IngestJoin__SPMM.sh /YieldWorkflow/IngestJoin__SPMM.sh
hadoop fs -put IngestJoin__SPDV.sh /YieldWorkflow/IngestJoin__SPDV.sh
hadoop fs -put IngestJoin__SPTT.sh /YieldWorkflow/IngestJoin__SPTT.sh
hadoop fs -put IngestJoin__SPTM.sh /YieldWorkflow/IngestJoin__SPTM.sh
hadoop fs -put CreateJoin_.sh /YieldWorkflow/CreateJoin_.sh
hadoop fs -put IngestJoin__SPMX.sh /YieldWorkflow/IngestJoin__SPMX.sh
hadoop fs -put IngestJoin__SPMM.sh /YieldWorkflow/IngestJoin__SPMM.sh
hadoop fs -put IngestJoin__SPDV.sh /YieldWorkflow/IngestJoin__SPDV.sh
hadoop fs -put IngestJoin__SPTT.sh /YieldWorkflow/IngestJoin__SPTT.sh
hadoop fs -put IngestJoin__SPTM.sh /YieldWorkflow/IngestJoin__SPTM.sh
hadoop fs -put CreateJoin_.sh /YieldWorkflow/CreateJoin_.sh
hadoop fs -put IngestJoin__SPMX.sh /YieldWorkflow/IngestJoin__SPMX.sh
hadoop fs -put IngestJoin__SPMM.sh /YieldWorkflow/IngestJoin__SPMM.sh
hadoop fs -put IngestJoin__SPDV.sh /YieldWorkflow/IngestJoin__SPDV.sh
hadoop fs -put IngestJoin__SPTT.sh /YieldWorkflow/IngestJoin__SPTT.sh
hadoop fs -put IngestJoin__SPTM.sh /YieldWorkflow/IngestJoin__SPTM.sh
hadoop fs -put CreateJoin_.sh /YieldWorkflow/CreateJoin_.sh
hadoop fs -put IngestJoin__SPMX.sh /YieldWorkflow/IngestJoin__SPMX.sh
hadoop fs -put IngestJoin__SPMM.sh /YieldWorkflow/IngestJoin__SPMM.sh
hadoop fs -put IngestJoin__SPDV.sh /YieldWorkflow/IngestJoin__SPDV.sh
hadoop fs -put IngestJoin__SPTT.sh /YieldWorkflow/IngestJoin__SPTT.sh
hadoop fs -put IngestJoin__SPTM.sh /YieldWorkflow/IngestJoin__SPTM.sh
hadoop fs -put CreateJoin_.sh /YieldWorkflow/CreateJoin_.sh
hadoop fs -put IngestJoin__SPMX.sh /YieldWorkflow/IngestJoin__SPMX.sh
hadoop fs -put IngestJoin__SPMM.sh /YieldWorkflow/IngestJoin__SPMM.sh
hadoop fs -put IngestJoin__SPDV.sh /YieldWorkflow/IngestJoin__SPDV.sh
hadoop fs -put IngestJoin__SPTT.sh /YieldWorkflow/IngestJoin__SPTT.sh
hadoop fs -put IngestJoin__SPTM.sh /YieldWorkflow/IngestJoin__SPTM.sh

 
oozie  job  -oozie  http://prod-hubnamedaws01.sunpowercorp.com:11000/oozie  -config  yieldIngestProperties.properties  -run
